@startuml use_case_stock
left to right direction

actor "Chargé de Stock" as user

rectangle "StoreManager Pro" {

    ' =========================
    ' MENUS PRINCIPAUX
    ' =========================

    usecase "Gérer les approvisionnements" as A
    usecase "Produits et tiers" as PR


    ' =========================
    ' APPROVISIONNEMENTS
    ' =========================

    usecase "Afficher statistiques approvisionnements" as ASA
    usecase "Consulter bons de livraison" as CBL
    usecase "Voir lignes d'un BL" as VLB
    usecase "Réceptionner un BL" as RBL
    usecase "Approvisionner un produit" as APP


    ' =========================
    ' PRODUITS ET TIERS
    ' =========================

    usecase "Afficher statistiques produits et tiers" as ASP

    usecase "Consulter catalogue courant" as CCC
    usecase "Filtrer les produits" as FPR
    usecase "Ajouter un article" as AAA

    usecase "Consulter répertoire clients" as CRC
    usecase "Enregistrer un client" as ECL

    usecase "Consulter répertoire fournisseurs" as CRF
    usecase "Enregistrer un fournisseur" as EFR
}


' =========================
' CHARGÉ DE STOCK
' =========================

user --> A
user --> PR


' =========================
' APPROVISIONNEMENTS
' =========================

A ..> ASA : <<include>>
A ..> CBL : <<include>>
A ..> APP : <<include>>

CBL ..> VLB : <<extend>>
CBL ..> RBL : <<extend>>


' =========================
' PRODUITS ET TIERS
' =========================

PR ..> ASP : <<include>>
PR ..> CCC : <<include>>
PR ..> CRC : <<include>>
PR ..> CRF : <<include>>

CCC ..> FPR : <<extend>>
CCC ..> AAA : <<extend>>

CRC ..> ECL : <<extend>>

CRF ..> EFR : <<extend>>

@enduml