@startuml use_case_inventaire
left to right direction

actor "Inventaire" as user

rectangle "StoreManager Pro" {

    ' =========================
    ' MENU PRINCIPAL
    ' =========================

    usecase "Produits et tiers" as PR


    ' =========================
    ' PRODUITS ET TIERS
    ' =========================

    usecase "Afficher statistiques produits et tiers" as ASP

    usecase "Consulter catalogue courant" as CCC
    usecase "Filtrer les produits" as FPR

    usecase "Consulter répertoire clients" as CRC

    usecase "Consulter répertoire fournisseurs" as CRF
}


' =========================
' INVENTAIRE
' =========================

user --> PR


' =========================
' PRODUITS ET TIERS
' =========================

PR ..> ASP : <<include>>
PR ..> CCC : <<include>>
PR ..> CRC : <<include>>
PR ..> CRF : <<include>>


' =========================
' CATALOGUE
' =========================

CCC ..> FPR : <<extend>>

@enduml