@startuml use_case_admin
left to right direction

actor "Admin Boutique" as user

rectangle "StoreManager Pro" {

    ' MODULES PRINCIPAUX

    usecase "Consulter le tableau de Bord" as TB
    usecase "lister les ventes" as VP
    usecase "gerer les dettes" as GD
    usecase "Gerer les approvisionnement" as A
    usecase "Consulter les Produits et tiers" as PR

    ' TABLEAU DE BORD

    usecase "Afficher statistiques" as STAT
    usecase "Consulter les ventes récentes" as CVR
    usecase "Consulter les dettes du jour" as CDJ
    usecase "Consulter les ruptures et alertes" as CRA
    usecase "Consulter les livraisons du jour" as CLJ
    usecase "Voir les clients débiteurs" as VCD
    usecase "Voir les soldes fournisseurs" as VSF

    usecase "Approvisionner un produit" as APP
    usecase "Valider un bon de livraison" as VBL
    usecase "Voir détail fournisseur" as VDF
    usecase "Payer un fournisseur" as PF


    ' VENTE / POS

    usecase "Afficher statistiques ventes" as ASV
    usecase "Consulter registre des ventes" as CRV
    usecase "Créer une nouvelle vente" as CNV
    usecase "Sélectionner client acheteur" as SCA
    usecase "Ajouter article au panier" as AAP
    usecase "Valider la vente" as VDV
    usecase "Voir lignes de commande" as VLC


    ' GESTION DETTES

    usecase "Afficher statistiques dettes" as ASD
    usecase "Consulter registre des dettes actives" as CRDA
    usecase "Rechercher un client" as RCH
    usecase "Voir articles d'une dette" as VAD
    usecase "Voir paiements d'une dette" as VPD
    usecase "Rembourser une dette" as RBD

    ' APPROVISIONNEMENT

    usecase "Afficher statistiques approvisionnements" as ASA
    usecase "Consulter bons de livraison" as CBL
    usecase "Voir lignes d'un BL" as VLB
    usecase "Réceptionner un BL" as RBL

    ' PRODUITS ET TIERS

    usecase "Afficher statistiques produits et tiers" as ASP

    usecase "Consulter catalogue courant" as CCC
    usecase "Filtrer les produits" as FPR
    usecase "Ajouter un article" as AAA

    usecase "Consulter répertoire clients" as CRC
    usecase "Enregistrer un client" as ECL

    usecase "Consulter répertoire fournisseurs" as CRF
    usecase "Enregistrer un fournisseur" as EFR
}

' ADMIN

user --> TB
user --> VP
user --> GD
user --> A
user --> PR

' TABLEAU DE BORD

TB ..> STAT : <<include>>
TB ..> CVR : <<include>>
TB ..> CDJ : <<include>>
TB ..> CRA : <<include>>
TB ..> CLJ : <<include>>
TB ..> VCD : <<include>>
TB ..> VSF : <<include>>

CRA ..> APP : <<extend>>
APP ..> VBL : <<include>>

VSF ..> VDF : <<extend>>
VSF ..> PF : <<extend>>

' VENTE / POS

VP ..> ASV : <<include>>
VP ..> CRV : <<include>>
VP ..> CNV : <<include>>

CNV ..> SCA : <<include>>
CNV ..> AAP : <<include>>
CNV ..> VDV : <<include>>

CRV ..> VLC : <<extend>>

' DETTES

GD ..> ASD : <<include>>
GD ..> CRDA : <<include>>
GD ..> RCH : <<include>>

CRDA ..> VAD : <<extend>>
CRDA ..> VPD : <<extend>>
CRDA ..> RBD : <<extend>>

' APPROVISIONNEMENT

A ..> ASA : <<include>>
A ..> CBL : <<include>>

CBL ..> VLB : <<extend>>
CBL ..> RBL : <<extend>>

' PRODUITS ET TIERS

PR ..> ASP : <<include>>
PR ..> CCC : <<include>>
PR ..> CRC : <<include>>
PR ..> CRF : <<include>>

CCC ..> FPR : <<extend>>
CCC ..> AAA : <<extend>>

CRC ..> ECL : <<extend>>

CRF ..> EFR : <<extend>>

@enduml